# Generated by Django 4.2.1 on 2024-03-23 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.IntegerField(unique=True, verbose_name="患者编号")),
                ("patient_name", models.CharField(max_length=65, verbose_name="患者姓名")),
                (
                    "patient_age",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="患者年龄",
                    ),
                ),
                (
                    "patient_sex",
                    models.CharField(
                        blank=True,
                        choices=[("0", "女性"), ("1", "男性")],
                        max_length=2,
                        null=True,
                        verbose_name="患者性别",
                    ),
                ),
                (
                    "patient_department",
                    models.CharField(default="心电", max_length=60, verbose_name="检测类型"),
                ),
                (
                    "patient_ecg",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="static/patient/%Y/%m/%d/",
                        verbose_name="心电记录",
                    ),
                ),
                (
                    "diagnosis_result",
                    models.TextField(blank=True, null=True, verbose_name="诊断结果"),
                ),
                (
                    "patient_telephone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="患者电话"
                    ),
                ),
                (
                    "create_by",
                    models.CharField(
                        default="doctor", max_length=64, verbose_name="创建人"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_by",
                    models.CharField(
                        default="doctor", max_length=64, verbose_name="更新人"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "患者名单",
                "verbose_name_plural": "患者名单",
                "db_table": "tb_patient",
            },
        ),
        migrations.DeleteModel(
            name="PatientManage",
        ),
    ]
