# Generated by Django 4.2.1 on 2024-03-23 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_patient_delete_patientmanage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Patient",
            new_name="PatientManage",
        ),
    ]
